defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      isOriginal: false
      hasOriginal: false

markdown: redcarpet

redcarpet:
  extensions: [smart, tables]